blank_issues_enabled: false

contact_links:
  - name: 💬 کانال تلگرام پشتیبانی
    url: https://t.me/movinestir
    about: برای پرسش‌های سریع یا پیشنهادات لحظه‌ای به کانال ما بپیوندید.

  - name: 📧 پشتیبانی ایمیل
    url: -
    about: اگر مسئله‌ای خصوصی دارید، می‌توانید ایمیل بزنید.

  - name: ❓ راهنمای سریع
    url: https://github.com/D3lusn/Movinest/blob/main/README.md
    about: حتماً ابتدا README پروژه را بخوانید، شاید پاسخ سوال شما آنجا باشد.
